config/routes.rb
DemoApp::Application.routes.draw do
  root to: 'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete' 
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions  ,   only: [:new, :create, :destroy]
  resources :microposts,   only: [:create, :destroy]
  resources :relationships,only: [:create, :destroy]

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  attr_accessible :content, :user_id
  validates :content , presence: true,  length: { maximum: 140 } #非空，长度140
  validates :user_id , presence: true
  belongs_to :user #user与 Microposts 1:n
  default_scope -> {order('created_at DESC') }

  def self.from_users_followed_by(user)
    #followed_user_ids = user.followed_user_ids 
    #where("user_id IN (?) OR user_id = ? ",followed_user_ids,user ) 
    #where("user_id IN (:followed_user_ids) OR user_id = user_id ",
    #   followed_user_ids: followed_user_ids,user_id: user )
    followed_user_ids = "SELECT followed_id FROM relationships WHERE  follower_id = :user_id " 
    where("user_id IN (#{followed_user_ids}) OR user_id = user_id ",
           user_id: user.id )
  end
end
 

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController 
  before_filter :signed_in_user, only: [:create,:destroy]
  before_filter :correct_user, only: [:destroy]
 
  def create
    #binding.pry 
    @micropost = current_user.microposts.build(params[:micropost])
    #@micropost = current_user.microposts.build(micropost_params)
    #binding.pry
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_path 
    else
      @feed_items = []
      render 'static_pages/home' 
    end
  end
 
 
  def destroy 
    #binding.pry 
    @micropost.destroy
    redirect_to root_path 
  end

  private

    def micropost_params
      params.require(:micropost).permit(:content)
    end
    #def correct_user
    #  @micropost = current_user.microposts.find(params[:id])
    #rescue
    #  redirect_to root_url 
    #end
    def correct_user
      @micropost = current_user.microposts.find_by_id(params[:id])
      redirect_to root_path if @micropost.nil?
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
  #换行显示长单词的帮助方法
  def wrap(content)
    sanitize(raw(content.aplit.map {|s| wrap_long_string(s)}.join(' ')))
  end

  private
  
    def wrap_long_string(text, max_width = 30)
      zero_width_space = "&#8203;"
      regex = /.{1,#{max_width}}/
      (text.length < max_width ) ? text :
                                   text.scan(regex).join(zero_width_space)
    end
end

app/views/microposts/_form.html.erb
<%= form_for(@micropost) do |f| %>
  <% if @micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% @micropost.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :conten %><br />
    <%= f.text_field :conten %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/microposts/_micropost.html.erb
<li>
  <span class="content"> <%= micropost.content %> </span>
  <span class="timestamp"> 
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
  </span>
  <%if current_user?(micropost.user) %> 
    <%= link_to 'delete', micropost, confirm: 'Are you sure?', method: :delete, title: micropost.content %>  <br />
  <% end %>
</li>

app/views/microposts/edit.html.erb
<h1>Editing micropost</h1>

<%= render 'form' %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

app/views/microposts/index.html.erb
<h1>Listing microposts</h1>

<table>
  <tr>
    <th>Conten</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @microposts.each do |micropost| %>
  <tr>
    <td><%= micropost.conten %></td>
    <td><%= micropost.user_id %></td>
    <td><%= link_to 'Show', micropost %></td>
    <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
    <td><%= link_to 'Destroy', micropost, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Micropost', new_micropost_path %>

app/views/microposts/new.html.erb
<h1>New micropost</h1>

<%= render 'form' %>

<%= link_to 'Back', microposts_path %>

app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Conten:</b>
  <%= @micropost.conten %>
</p>

<p>
  <b>User:</b>
  <%= @micropost.user_id %>
</p>


<%= link_to 'Edit', edit_micropost_path(@micropost) %> |
<%= link_to 'Back', microposts_path %>